apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
  namespace: dishes
spec:
  limits:
  - default: # this section defines default limits
      cpu: 20m
    defaultRequest: # this section defines default requests
      cpu: 10m
    max: # max and min define the limit range
      cpu: "40m"
    min:
      cpu: 10m
    type: Container
